const AIDEN_TRUST_CLIENT_THEME_KEY = 'AIDEN_TRUST_CLIENT_THEME_KEY';
const AIDEN_TRUST_CLIENT_TOKEN_KEY = 'AIDEN_TRUST_CLIENT_TOKEN_KEY';
const AIDEN_TRUST_CLIENT_AUTH_DATA_KEY = 'AIDEN_TRUST_CLIENT_AUTH_DATA_KEY';
// const URL_BASE_SERVER = 'http://localhost:7008/api/v1/user';
// const URL_BASE_SERVER = 'https://aidentrust.herokuapp.com/api/v1/user';
const URL_BASE_SERVER = 'https://aidentrust.onrender.com/api/v1/user';

export const CONSTANTS = {
    AIDEN_TRUST_CLIENT_THEME_KEY,
    URL_BASE_SERVER,
    AIDEN_TRUST_CLIENT_AUTH_DATA_KEY,
    AIDEN_TRUST_CLIENT_TOKEN_KEY
};
