const AIDEN_TRUST_CLIENT_THEME_VARIANT_KEY = 'AIDEN_TRUST_CLIENT_THEME_VARIANT_KEY';
const AIDEN_TRUST_CLIENT_AUTH_DATA_KEY = 'AIDEN_TRUST_CLIENT_AUTH_DATA_KEY';
const AIDEN_TRUST_CLIENT_TOKEN_KEY = 'AIDEN_TRUST_CLIENT_TOKEN_KEY';

export const CONSTANTS = {
    AIDEN_TRUST_CLIENT_THEME_VARIANT_KEY,
    AIDEN_TRUST_CLIENT_AUTH_DATA_KEY,
    AIDEN_TRUST_CLIENT_TOKEN_KEY
};
