const AIDEN_TRUST_CLIENT_THEME_VARIANT_KEY = 'AIDEN_TRUST_CLIENT_THEME_VARIANT_KEY';
const AIDEN_TRUST_CLIENT_AUTH_DATA_KEY = 'AIDEN_TRUST_CLIENT_AUTH_DATA_KEY';
const AIDEN_TRUST_CLIENT_TOKEN_KEY = 'AIDEN_TRUST_CLIENT_TOKEN_KEY';
const SERVER_BASE_URL = 'SERVER_BASE_URL';

export const CONSTANTS = {
    AIDEN_TRUST_CLIENT_THEME_VARIANT_KEY,
    SERVER_BASE_URL,
    AIDEN_TRUST_CLIENT_AUTH_DATA_KEY,
    AIDEN_TRUST_CLIENT_TOKEN_KEY
};
